### PR TITLE
File size

### PR DESCRIPTION
**Pull request by Syntactical01**
Converted entrypoint.sh too entrypoint.py. Opening PR to have a discussion.

### CODE REVIEW

**Comment by mneil** [comment]
I started going down this path in a fork month ago but stopped because it wasn't adding value. That said, if this works, IMO, we should use it. But... a caveat.
 
Why python over bash?
 
 - It's a language with more robust expressions
 - It's easier to read
 - You can more easily lint and write tests for it
 
The last one... tests... is why I originally started switching off of bash. There are no tests for this file. I personally wouldn't accept it as is until you can prove it's logically correct. It looks good, but can you test that it does all the things the current one does and doesn't introduce a new error. We've already broken the packager a few times with pushes because bash is untested or not tested enough.

**Comment by ktruckenmiller** [comment]
I don't have opinions as long as it's more testable and usable. Do we have any opinions on integrating our HTTPS / SSH flipping functionality into this for private repos

**Comment by Syntactical01** [comment]
> I don't have opinions as long as it's more testable and usable. Do we have any opinions on integrating our HTTPS / SSH flipping functionality into this for private repos

Not only could we do that... We can also implement that functionality in requirement.txt files not just setup.py files.

**Comment by Syntactical01** [comment]
TODO:
- Unit Testing
- Integration Testing
- SSH/HTTPS flipping (This should best be done in a different branch)

**Pull request merged**
